//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareFile.Api.Powershell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareFile.Api.Powershell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareFile.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOdm0AhEu7RclDqhC5vKtpcyyJrdcGSK.
        /// </summary>
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8VR4WXDZ30CThAyo9cnXaDeC2xyFP5e1wDKPujYrpBfGmtXy.
        /// </summary>
        internal static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sf-api.com.
        /// </summary>
        internal static string DefaultApiDomain {
            get {
                return ResourceManager.GetString("DefaultApiDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v3.
        /// </summary>
        internal static string DefaultApiVersion {
            get {
                return ResourceManager.GetString("DefaultApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secure.
        /// </summary>
        internal static string DefaultGlobalApiSubdomain {
            get {
                return ResourceManager.GetString("DefaultGlobalApiSubdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLog.config.
        /// </summary>
        internal static string LogConfigFile {
            get {
                return ResourceManager.GetString("LogConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main.log.
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string MaxExceptionRetry {
            get {
                return ResourceManager.GetString("MaxExceptionRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ProgressFile {
            get {
                return ResourceManager.GetString("ProgressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.sharefile.com/oauth/oauthcomplete.aspx.
        /// </summary>
        internal static string RedirectURL {
            get {
                return ResourceManager.GetString("RedirectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sf.
        /// </summary>
        internal static string ShareFileProvider {
            get {
                return ResourceManager.GetString("ShareFileProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.9.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
